version: "3.8"

networks:
    app-network:

services:
    oldwave-nginx-container:
        build:
            context: .docker/nginx
            dockerfile: Dockerfile
        container_name: oldwave-nginx-container
        restart: unless-stopped
        ports:
            - "80:80"
        networks:
            app-network:

    oldwave-api-container:
        build:
            context: .docker/php
            dockerfile: dockerfile
        container_name: oldwave-api-container
        networks:
            app-network:
