version: "3.8"

volumes:
    app-data:

services:
    oldwave-api-container:
        build:
            context: .docker/php
            dockerfile: dockerfile
        image: oldwave_api
        container_name: oldwave-api-container
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        restart: unless-stopped
