version: "3.8"

services:
    backend:
        build:
            dockerfile: Dockerfile
        image: oldwave_api
        container_name: backend
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
        restart: unless-stopped
