version: "3.8"

services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        image: oldwave_api
        container_name: backend
        ports:
            - "80:80"
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
